include:
  - board: nice_nano//zmk
    shield: charybdis_dongle dongle_display
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y

  - board: xiao_ble/nrf52840/zmk
    shield: charybdis_dongle_prospector prospector_adapter
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y

  - board: nice_nano//zmk
    shield: charybdis_left
    # snippet: zmk-usb-logging
    # cmake-args: -DCONFIG_ZMK_USB_LOGGING=y

  - board: nice_nano//zmk
    shield: charybdis_right

  - board: nice_nano//zmk
    shield: charybdis_right_central

  - board: nice_nano//zmk
    shield: charybdis_left_encoder

  - board: nice_nano//zmk
    shield: settings_reset

  - board: xiao_ble/nrf52840/zmk
    shield: settings_reset
